services:
  was:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - "8081:5000"
    restart: always
    networks:
      - service

networks:
  service: